# Site settings
title: DOMINOMATRIX
description: "星野謙太の個人サイトです。Web制作に関して勉強したことや備忘録などを綴っています。現在はDeveloperを目指し目下勉強中です。最近の興味はアクセシビリティ。"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:9989" # the base hostname & protocol for your site


# Author
name: Dominomatrix
author:
  name: Kenta Hoshino
  firstname: Kenta
  lastname: Hoshino
  handlename: kenty
  image: FB-Itsme.jpg

email: kent6223@gmail.com
social:
  twitter: "https://twitter.com/kenty236"
  facebook: "https://www.facebook.com/kenty236"
  instagram: "https://instagram.com/kenty236"
  github: "https://github.com/Kenty"
  pinterest: "https://jp.pinterest.com/kenty236"
twitter_username: kenty236
github_username:  kenty

# navigation bar options
navi-links:
 - title: Blog
   url: "/blog/"
 - title: About
   url: "/about/"

# Build settings
source: ./app
destination: ./build

permalink: /blog/:title
paginate: 5
paginate_path: "blog/page/:num"

safe: true
server: true
lsi: false

markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
auto: true

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: auto

exclude: [
  'vendor',
  'Gemfile',
  'Gemfile.lock',
  '.ruby-version',
  '.gitignore',
  '.bundle',
  '.git',
  'LICENSE'
]
