# Site settings
title: DOMINOMATRIX
description: "星野謙太の個人サイトです。Web制作に関して勉強したことや備忘録、また興味のあることを綴っていこうと思っています。現在はWeb制作の仕事に就けるように勉強中です。最近の興味はアクセシビリティ。"
baseurl: ""
url: "http://localhost:9989"


# Author
name: Dominomatrix
author:
  name: Kenta Hoshino
  firstname: Kenta
  lastname: Hoshino
  handlename: kenty
  image: FB-Itsme.jpg

email: kent6223@gmail.com
social:
  twitter: "https://twitter.com/kenty236"
  facebook: "https://www.facebook.com/kenty236"
  app_id: "264826913608312"
  instagram: "https://instagram.com/kenty236"
  github: "https://github.com/Kenty"
  pinterest: "https://jp.pinterest.com/kenty236"
twitter_username: kenty236
github_username:  kenty

# Build settings
source: ./app
destination: ./build

permalink: /blog/:title
paginate: 3
paginate_path: "/blog/page:num"

safe: false
lsi: false
incremental: true

markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: auto

exclude: [
  'vendor',
  'Gemfile',
  'Gemfile.lock',
  '.ruby-version',
  '.gitignore',
  '.bundle',
  '.git',
  'LICENSE',
  'aws.json'
]

gems: [jekyll-paginate]
